spring.application.name: employee-api
server.port: 8111

# Mock API Configuration
mock:
  api:
    base-url: http://localhost:8112

# Logging Configuration
logging:
  level:
    com.reliaquest: DEBUG
